<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\ZaraShellIcon.ico</ApplicationIcon>
    <StartupObject>Zara.Desktop.Program</StartupObject>
    <AssemblyName>Zara.Desktop</AssemblyName>
    <RootNamespace>Zara.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zara.Application\Zara.Application.csproj" />
    <ProjectReference Include="..\Zara.Infrastructure.Windows\Zara.Infrastructure.Windows.csproj" />
    <ProjectReference Include="..\Zara.Supervision.Contracts\Zara.Supervision.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\ZaraIcon.ico" />
    <Resource Include="Assets\ZaraIcon.png" />
    <Resource Include="Assets\ZaraShellIcon.ico" />
    <Resource Include="Assets\ZaraShellIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Presets\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Compile Remove="LocalBuilds\**\*.cs" />
    <Page Remove="LocalBuilds\**\*.xaml" />
  </ItemGroup>

</Project>
